### PR TITLE
add PDM digital mems mic SPH0641LM4H-1

### PR DESCRIPTION
**Pull request by lewispg228**

### CODE REVIEW

**Comment by lewispg228** [comment]
FYI, I had a bit of trouble getting the paste layer around the mic port on this correct. I ultimately used the dxf ulp tool from the older eagle library, and then imported into KiCad as a graphic. It did work, but it seems to have some tiny artifacts. Its probably 
 okay as is, but I'll keep digging into a better way to create unique paste patterns like this in KiCad. Thanks for reviewing!

image

**Comment by lewispg228** [comment]
Ah, just thought to look at the built-in kicad options for a similar mic... they do it with arcs lines. I'll get this adjusted shortly.

image

**Comment by lewispg228** [comment]
Looks much better as arcs. And that was much easier this time around. 
image

**Comment by nseidle** [comment]
Nice! I added a courtyard: 
image

Took down caps:
image

**Review by nseidle — APPROVED** [review]

**Pull request merged**
