### PR TITLE
ap7351C-FGE-7 symbol and 8-UDFN footprint

### PR DESCRIPTION
**Pull request by lewispg228**

### CODE REVIEW

**Comment by nseidle** [comment]
Does the Exposed pad need a pin connection?

**Comment by lewispg228** [comment]
Good call. Added. 

Note, the datasheet doesn't really state that connecting this to GND is correct. From the paragraph about Power Dissipation (page 12), it sounds like it should be connected to it's own "thermal plane". Therefore, keeping it on it's own separate pin on the left side of the symbol sounded like a good idea.

image

**Comment by SFE-Brudnerd** [comment]
Per the first page in the datasheet, it should be connected to ground. Thermal plane is more referring to needing a large copper plane to dissipate heat into in order to get the heat out of the package.
image

**Comment by lewispg228** [comment]
Thanks for that correction. I moved the EP pin to the bottom of the symbol (right next to GND). Should make for cleaner schematics and encourage designers to properly ground the EP.

**Review by nseidle — APPROVED** [review]

**Comment by nseidle** [comment]
Looks good! Thanks!

**Pull request merged**
