### PR TITLE
Add push buttons and switches

### PR DESCRIPTION
**Pull request by nseidle**

### CODE REVIEW

**Comment by PaulZC** [comment]
This is looking good. The only gremlins I've spotted are:

- The spoke angles are 45 (on SMD_5.2x5.2mm_h1.9mm)

image

- I get a warning about pins 2 and 4 (on SMD_5.2x5.2mm_h1.9mm)
  - Some hidden not-connected symbol pins would make these go away...

image

**Review by PaulZC — CHANGES_REQUESTED** [review]
Please fix the thermal bridge (spoke) angle on several footprints...

Otherwise, looks very good!

**Comment by nseidle** [comment]
Agreed all around. I made the SMD buttons reflect what seems to be the KiCad standard of 1/1 2/2 on four pin buttons: 
image

It means we have to double the routing, but I'm ok with this. It avoids NC ghost pins and potentials leads to less production issues (double the pads may mean less button failures).

**Comment by nseidle** [comment]
I think all had been fixed.

**Comment by PaulZC** [comment]
OK. This looks better - thanks!

I've really only checked the 5.2x5.2. I'm assuming all the other are equally good...!

image

**Review by PaulZC — APPROVED** [review]

**Pull request merged**
