### PR TITLE
Panasonic_ capacitor footprint case change

### PR DESCRIPTION
**Pull request by PaulZC**
We've fallen foul of the Git-doesn't-like-file-name-case-changes-only gremlin.
The symbols are pointing to Panasonic_C and _D.
But the footprint file names were still PANASONIC_C and _D.
The only fix I've come up with is to: delete the files, commit, re-add the files (with the case change), commit.
It fails if you (only): change the file name case, commit.

### CODE REVIEW

**Comment by PaulZC** [comment]
I've also fixed the Panasonic_C footprint. The origin was off, and it was missing courtyard. We're not using it yet - so the change won't break anything.

I've also moved all User.1 lines and text to F.Fab. Why? It's really handy to use User.1 for Milling - e.g. the voltage gap under PoE. (Otherwise you need to find another empty layer for Milling and remember to tick that box when running the CAMmer.)

**Comment by PaulZC** [comment]
The new SparkFun-Semiconductor-Nonstandard folder was missing ".pretty".
I'm not sure how important that is. It was working without it. But I've corrected it anyway.
**Note:** you will need to change the folder name in Footprint Editor \ Manage Footprint Libraries to match

**Comment by PaulZC** [comment]
Bump @nseidle

**Comment by nseidle** [comment]
So many changes. Ok, when you change the layer on FPs from User to F.Fab (a good change) KiCad is adding thicknesses to unused fields. Fine.
...
All looks good!

**Comment by PaulZC** [comment]
Nice one - thanks!

**Pull request merged**
