### PR TITLE
Add SMD CBI LED Footprints

### PR DESCRIPTION
**Pull request by NPoole**
- Add Single and 4-Gang SMD CBI Assembly footprints
- Add APA102-2020 footprint
- Add APA102-2020 symbol

### CODE REVIEW

**Comment by sfe-SparkFro** [comment]
The reference designator is in the Silkscreen layer, should be Fab

image

**Comment by sfe-SparkFro** [comment]
Also, the holes are missing cutouts for the top and bottom solder mask

**Comment by sfe-SparkFro** [comment]
Actually, the holes are defined as edge cuts. IMO would be better to define them as actual holes, similar to the USB-C footprint. Set the type to "NPTH, Mechanical", then select "None" under "Copper layers". The "Pad shape" determines the soldermask, and the "Hole shape" determines the hole itself.

**Comment by nseidle** [comment]
I made a bunch of changes on my local copy (added courtyard, etc). I'm going to close this, open a new one with my changes, and add your changes @sfe-SparkFro. BRB.

**Pull request closed without merging**
