### PR TITLE
add 12pF, 20pF, 32.768KHz

### PR DESCRIPTION
**Pull request by lewispg228**

### CODE REVIEW

**Comment by nseidle** [comment]
I jumped on this because I need this parts but no love: 

image

**Comment by lewispg228** [comment]
I created this using KiCad 8.0. I thought we were all upgrading?

**Comment by nseidle** [comment]
Negative. We're still getting the tool chain upgraded to be compatible with v8. Until that time v7 is where we're at.

**Comment by PaulZC** [comment]
@lewispg228 : how easy was it to use the 7 library in 8? Did you have any issues? Thanks!

**Comment by nseidle** [comment]
Alright @lewispg228 - We've got the repo updated to v8. Please rebase your PR and I'll have a look.

**Comment by lewispg228** [comment]
These parts are already in the library. Closing this PR.

**Pull request closed without merging**
