### PR TITLE
Add RP2350

### PR DESCRIPTION
**Pull request by sfe-SparkFro**
RP2350A, RP2350B, and special inductor for RP2350

### CODE REVIEW

**Comment by nseidle** [comment]
Can you remove the unique labeling for a standard IC package (QFN-60)?

image

Or go big:

image

https://grabcad.com/library/qfn-60-rp2350a-1
https://grabcad.com/library/rp2350-1

**Comment by sfe-SparkFro** [comment]
Good catch! Will change to a generic QFN-60 package so the 3D model can be used by any QFN-60 chip.

**Comment by sfe-SparkFro** [comment]
Done!

**Comment by nseidle** [comment]
Blank QFNs look good. Thanks!

image

**Pull request merged**
