### PR TITLE
Usbpd parts

### PR DESCRIPTION
**Pull request by lewispg228**

### CODE REVIEW

**Comment by nseidle** [comment]
image

image

image

Is the POWERDVFN really unique or should it be in the Semiconductor-Standard library? 

Would it make sense to combine pads 5/6/7 into one pad? You may see DRC errors down the road if you don't. 

TVS diode looks good.

STLP MOSFET symbol looks good.

**Comment by lewispg228** [comment]
Well, in the process of updating the name to PowerFLAT, I found the "6" version in the Package_SON library (ST_PowerFLAT-6L_5x6mm_P1.27mm). 

Maybe it should go in the Package_SON library. I'll look into doing a PR there next.

image

**Comment by nseidle** [comment]
Let me know when you're ready for another review.

**Comment by lewispg228** [comment]
Hey @nseidle ,
This PR is ready for another review. 
Thanks!

PS Sorry for the delay and mis-understanding here. When I read "Standard", I thought you meant [these Kicad Libraries](https://gitlab.com/kicad/libraries). After going down that rabbit hole, I have now moved it into our SparkFun-Semiconductor-Standard libraries.

**Review by nseidle — APPROVED** [review]

**Pull request merged**
